### ISSUE TITLE
Various Questions about your project

### ISSUE THREAD

**Issue by mwittig** [FROeHlyEisvogel/Smart-ClimaSens#1]
I have a few questions regarding your nice and well documented project. If you haven't done already it'll be really nice if you introduce your project and pimatic plugin on [Pimatic Forum](https://forum.pimatic.org/) to make it more visible to the pimatic user community.
* I am just asking out of curiosity. Did you create this project as part of your studies, at school, or is it meant to be for educational purposes?
* Are you ready to further maintain the project?
* What is your experience wrt to battery lifetime? 
* Why did you use a button cell rather than batteries with higher capacity?

**Comment by FROeHlyEisvogel** [comment]
That's a good idea I will think about it.

- I build the project just for myself and want to share the knowledge with other people.

- Until now there is not much attention to this project so I update it from time to time. If it is becoming more fameous I will have to think about how much time I can invest.

- There are six sensors installed at my home since half a year and they are still running with the first battery. The calculated life time from measurements is up to 5 years. It is difficult to estimate the battery charge from the measured voltage because the voltage depends on the current temperature. But I would say that there is noticeable voltage drop until now.

- The button cell is used cause of cost and size reasons. Also it is compatible with the controller voltage and no other hardware is needed.

P.S. I am currently working on a powermeter to measure the current power on digital electric meters based on the same hardware like the luminance sensor.

**Comment by mwittig** [comment]
Thank you very much for your feedback.
